/**
 * Cloudflare Worker — Contact form endpoint for ruslanmv.com
 *
 * Flow:
 *   /contact page  →  POST JSON  →  THIS Worker  →  Resend API  →  email
 *
 * The Worker sends TWO emails on a valid submission:
 *   1) NOTIFICATION  → to Ruslan (contact@ruslanmv.com)
 *   2) CONFIRMATION  → an automatic, professional acknowledgement to the sender
 *
 * The Resend API key lives ONLY here as a Worker secret (env.RESEND_API_KEY).
 * It is NEVER exposed to the browser or committed to the repo.
 *
 * Domain ruslanmv.com is verified in Resend (DKIM + SPF), so we send from
 * the real domain. See SETUP-GUIDE.md to deploy.
 *
 * FUTURE: the auto-confirmation body is generated by buildConfirmationEmail().
 * To swap in an AI-written reply later, make that function call your AI model
 * (e.g. another Worker / Anthropic API) and return { subject, html, text }.
 * Nothing else needs to change.
 */

const ALLOWED_ORIGINS = [
  "https://ruslanmv.com",
  "https://www.ruslanmv.com",
  "http://localhost:4000",
  "http://127.0.0.1:4000",
];

const CORS_BASE = {
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

function corsHeaders(origin) {
  const allow = ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0];
  return { ...CORS_BASE, "Access-Control-Allow-Origin": allow };
}

function json(body, status, origin) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...corsHeaders(origin) },
  });
}

// Escape user input before putting it into HTML.
const esc = (s) =>
  String(s).replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

// Send one email through Resend. Returns the parsed response.
async function sendEmail(env, payload) {
  const r = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${env.RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });
  const detail = await r.text();
  return { ok: r.ok, status: r.status, detail };
}

/* ------------------------------------------------------------------ *
 *  1) Notification email — to Ruslan
 * ------------------------------------------------------------------ */
function buildNotificationEmail({ name, email, topic, message }) {
  const subject = `[ruslanmv.com] ${topic} — ${name}`;
  const html = `
    <div style="font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;max-width:600px">
      <h2 style="color:#0b5a3f;margin:0 0 16px">New contact message from ruslanmv.com</h2>
      <table style="border-collapse:collapse;width:100%;font-size:15px">
        <tr><td style="padding:6px 0;color:#6c726c;width:90px">Name</td><td style="padding:6px 0;color:#1c2320"><strong>${esc(name)}</strong></td></tr>
        <tr><td style="padding:6px 0;color:#6c726c">Email</td><td style="padding:6px 0"><a href="mailto:${esc(email)}" style="color:#0a7d4f">${esc(email)}</a></td></tr>
        <tr><td style="padding:6px 0;color:#6c726c">Topic</td><td style="padding:6px 0;color:#1c2320">${esc(topic)}</td></tr>
      </table>
      <p style="margin:16px 0 6px;color:#6c726c">Message</p>
      <div style="background:#f6f6f3;border:1px solid #e7e6df;border-radius:10px;padding:14px;color:#1c2320;white-space:pre-wrap;font-size:15px;line-height:1.5">${esc(message)}</div>
      <p style="margin:18px 0 0;color:#98a09a;font-size:13px">Reply directly to this email to respond to ${esc(name)}.</p>
    </div>`;
  const text =
    `New contact message from ruslanmv.com\n\n` +
    `Name: ${name}\nEmail: ${email}\nTopic: ${topic}\n\nMessage:\n${message}\n`;
  return { subject, html, text };
}

/* ------------------------------------------------------------------ *
 *  2) Auto-confirmation email — to the sender
 *     (Later: replace the body with an AI-written reply.)
 * ------------------------------------------------------------------ */
function buildConfirmationEmail({ name, topic, message }) {
  const firstName = String(name).trim().split(/\s+/)[0] || "there";
  const subject = `Thanks for reaching out — I've received your message`;
  const html = `
    <div style="font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;max-width:600px;color:#1c2320">
      <div style="background:#08120d;border-radius:14px;padding:24px 26px;margin:0 0 22px">
        <p style="margin:0;color:#36e0a8;font-size:12px;letter-spacing:.18em;font-weight:700">RUSLANMV.COM</p>
        <h1 style="margin:8px 0 0;color:#ffffff;font-size:24px">Thanks, ${esc(firstName)} — message received</h1>
      </div>
      <p style="font-size:15px;line-height:1.6;margin:0 0 14px">
        Thank you for getting in touch regarding <strong>${esc(topic)}</strong>.
        This is an automatic confirmation that your message has reached me safely.
      </p>
      <p style="font-size:15px;line-height:1.6;margin:0 0 14px">
        I read every message personally and reply to relevant professional
        inquiries by email, usually within <strong>1–2 business days</strong>.
      </p>
      <p style="font-size:14px;color:#6c726c;margin:0 0 6px">For your records, here is what you sent:</p>
      <div style="background:#f6f6f3;border:1px solid #e7e6df;border-radius:10px;padding:14px;color:#1c2320;white-space:pre-wrap;font-size:14px;line-height:1.5;margin:0 0 20px">${esc(message)}</div>
      <p style="font-size:15px;line-height:1.6;margin:0 0 4px">Warm regards,</p>
      <p style="font-size:15px;line-height:1.6;margin:0">
        <strong>Ruslan Magana Vsevolodovna</strong><br>
        <span style="color:#6c726c">Machine Learning Engineer · Data Scientist · Physicist</span><br>
        <a href="https://ruslanmv.com" style="color:#0a7d4f">ruslanmv.com</a>
      </p>
      <hr style="border:none;border-top:1px solid #e7e6df;margin:22px 0">
      <p style="font-size:12px;color:#98a09a;margin:0">
        This is an automated confirmation from ruslanmv.com. Please don't reply to
        this message — I'll respond from my personal email shortly.
      </p>
    </div>`;
  const text =
    `Thanks, ${firstName} — message received\n\n` +
    `Thank you for getting in touch regarding "${topic}". This is an automatic ` +
    `confirmation that your message has reached me safely.\n\n` +
    `I read every message personally and reply to relevant professional inquiries ` +
    `by email, usually within 1-2 business days.\n\n` +
    `For your records, here is what you sent:\n${message}\n\n` +
    `Warm regards,\nRuslan Magana Vsevolodovna\n` +
    `Machine Learning Engineer · Data Scientist · Physicist\nhttps://ruslanmv.com\n\n` +
    `— This is an automated confirmation. Please don't reply to this message.`;
  return { subject, html, text };
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get("Origin") || "";

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeaders(origin) });
    }
    if (request.method !== "POST") {
      return json({ error: "Method not allowed" }, 405, origin);
    }

    let data;
    try {
      data = await request.json();
    } catch {
      return json({ error: "Invalid JSON" }, 400, origin);
    }

    const { name, email, topic, message, company, turnstileToken } = data || {};

    // Honeypot — a bot filled the hidden "company" field. Pretend success.
    if (company && String(company).trim() !== "") {
      return json({ ok: true }, 200, origin);
    }

    // Cloudflare Turnstile — only enforced when a secret is configured, so the
    // form keeps working before Turnstile is set up. The token is verified
    // server-side with Cloudflare (the frontend token alone is not trusted).
    if (env.TURNSTILE_SECRET_KEY) {
      if (!turnstileToken) {
        return json({ error: "Verification required" }, 400, origin);
      }
      try {
        const v = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", {
          method: "POST",
          headers: { "Content-Type": "application/x-www-form-urlencoded" },
          body: new URLSearchParams({
            secret: env.TURNSTILE_SECRET_KEY,
            response: String(turnstileToken),
            remoteip: request.headers.get("CF-Connecting-IP") || "",
          }),
        });
        const out = await v.json();
        if (!out.success) {
          return json({ error: "Verification failed" }, 403, origin);
        }
      } catch (e) {
        return json({ error: "Verification error" }, 502, origin);
      }
    }

    // Server-side validation
    if (!name || !email || !topic || !message) {
      return json({ error: "Missing required fields" }, 400, origin);
    }
    if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
      return json({ error: "Invalid email" }, 400, origin);
    }
    const msg = String(message);
    if (msg.length < 20 || msg.length > 4000) {
      return json({ error: "Message must be between 20 and 4000 characters" }, 400, origin);
    }

    // CONTACT_TO_EMAIL may be a single address or a comma-separated list, so
    // the notification can land in more than one inbox (e.g. your domain
    // address AND your Gmail). Every listed address receives the message.
    // This list is INTERNAL — it must never be shown to visitors.
    const TO = (env.CONTACT_TO_EMAIL || "contact@ruslanmv.com")
      .split(",").map((s) => s.trim()).filter(Boolean);
    const FROM = env.CONTACT_FROM_EMAIL || "Ruslan Magana Vsevolodovna <contact@ruslanmv.com>";
    // The only address ever exposed to visitors. Always the professional domain
    // address — never a personal/Gmail inbox, even if it's in CONTACT_TO_EMAIL.
    const PUBLIC_REPLY_TO = env.CONTACT_PUBLIC_EMAIL || "contact@ruslanmv.com";
    const payload = { name, email, topic, message: msg };

    // 1) Notification to Ruslan — this one must succeed.
    const notif = buildNotificationEmail(payload);
    const r1 = await sendEmail(env, {
      from: FROM,
      to: TO,
      reply_to: email,
      subject: notif.subject,
      html: notif.html,
      text: notif.text,
    });
    if (!r1.ok) {
      return json({ error: "Email send failed", detail: r1.detail }, 502, origin);
    }

    // 2) Auto-confirmation to the sender — best effort; never fail the request
    //    just because the confirmation didn't go out.
    try {
      const conf = buildConfirmationEmail(payload);
      await sendEmail(env, {
        from: FROM,
        to: [email],
        reply_to: PUBLIC_REPLY_TO, // never the internal TO list (no Gmail leak)
        subject: conf.subject,
        html: conf.html,
        text: conf.text,
      });
    } catch (_) {
      /* swallow — notification already delivered */
    }

    return json({ ok: true }, 200, origin);
  },
};
